name: PROD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: w9jds/firebase-action@master
      - name: Checkout	
        uses: actions/checkout@v2	
      - name: Use Node 12.x	
        uses: actions/setup-node@v1	
        with:	
          node-version: '12.x'
      - name: Install dependencies	
        run: npm ci	
      - name: Build	
        run: npm run build	
      - name: Set Firebase Prod
        run: firebase use prod --token ${{ secrets.FIREBASE_TOKEN }} 
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}   
      - name: Deploy to Firebase
        run: firebase use prod --token ${{ secrets.FIREBASE_TOKEN }} 
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  
